import AppKit
import ClippaCore
import ClippaPasteboard

/// Watches the system clipboard and turns every new copy into a
/// `CapturedContent`. macOS has no "clipboard changed" notification, so
/// like every clipboard manager it checks the change counter a few times a
/// second (a cheap call that reads no content).
@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onCapture: (RawCapture) -> Void

    /// Formats bigger than this are not saved (the others of the same copy are).
    private let maxRepresentationSize = 30 * 1024 * 1024
    /// Above this a whole copy keeps only its main formats.
    nonisolated static let maxTotalSize = 60 * 1024 * 1024

    /// What was read from the clipboard, before the slow work (thumbnails,
    /// image conversion), which `process` does off the main thread.
    struct RawCapture: Sendable {
        var representations: [CapturedRepresentation]
        var text: String
        var fileURLs: [URL]
        var sourceID: String?
        var sourceName: String?
    }

    init(onCapture: @escaping (RawCapture) -> Void) {
        self.onCapture = onCapture
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    var isPaused: Bool {
        guard let until = Pref.pausedUntilDate else { return false }
        if until > Date() { return true }
        Pref.pausedUntilDate = nil
        return false
    }

    private func check() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard !isPaused, let content = read() else { return }
        onCapture(content)
    }

    /// Reads the clipboard now, applying the privacy rules. Returns nil when
    /// the copy must be ignored.
    private func read() -> RawCapture? {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return nil }
        let allTypes = Set(items.flatMap { $0.types.map(\.rawValue) })

        // Clippa's own writes.
        if allTypes.contains(PasteboardWriter.ownType.rawValue) { return nil }
        let defaults = UserDefaults.standard
        if defaults.bool(forKey: Pref.ignoreConfidential), allTypes.contains(UTI.concealed) {
            Log.info("Copy ignored: marked confidential")
            return nil
        }
        if defaults.bool(forKey: Pref.ignoreTransient),
           allTypes.contains(UTI.transient) || allTypes.contains(UTI.autoGenerated) { return nil }

        // The app that copied: the one in front, unless the copy names its source.
        var sourceID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        var sourceName = NSWorkspace.shared.frontmostApplication?.localizedName
        if let declared = items.first?.string(forType: NSPasteboard.PasteboardType(UTI.source)), !declared.isEmpty {
            sourceID = declared
            sourceName = AppIcons.name(for: declared)
        }
        if let sourceID, Pref.ignoredAppIDs.contains(sourceID) {
            Log.info("Copy ignored: app in the ignore list")
            return nil
        }

        // Read every format of every pasteboard item.
        var representations: [CapturedRepresentation] = []
        for (index, item) in items.enumerated() {
            for type in item.types {
                let raw = type.rawValue
                if raw.hasPrefix("org.nspasteboard.") || raw == PasteboardWriter.ownType.rawValue { continue }
                guard let data = item.data(forType: type), data.count <= maxRepresentationSize else { continue }
                representations.append(CapturedRepresentation(index: index, type: raw, data: data))
            }
        }
        guard !representations.isEmpty else { return nil }

        let fileURLs = items.compactMap { $0.string(forType: .fileURL).flatMap(URL.init(string:)) }
        // HTML parsing must happen on the main thread, so the text is read here.
        let text = pasteboard.string(forType: .string) ?? Self.textFromFormatted(representations) ?? ""
        return RawCapture(representations: representations, text: text, fileURLs: fileURLs,
                          sourceID: sourceID, sourceName: sourceName)
    }

    /// Turns a raw copy into an item: kind, thumbnail, image size. Runs in
    /// the background. Returns nil when there is nothing worth saving.
    nonisolated static func process(_ raw: RawCapture) -> CapturedContent? {
        let representations = raw.representations
        let text = raw.text
        let fileURLs = raw.fileURLs
        let imageRep = preferredImage(in: representations)

        var content: CapturedContent
        if !fileURLs.isEmpty {
            let paths = fileURLs.map(\.path)
            content = CapturedContent(kind: .file, text: paths.joined(separator: "\n"),
                                      identity: paths.joined(separator: "\n"), representations: representations)
            // A single image file gets a real thumbnail.
            if fileURLs.count == 1, let data = try? Data(contentsOf: fileURLs[0], options: .mappedIfSafe),
               data.count < 80 * 1024 * 1024, ImageTools.pixelSize(of: data) != nil {
                content.thumbnail = ImageTools.thumbnail(of: data)
            }
        } else if let imageRep, text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                    || Classifier.link(text) != nil {
            // An image alone, or with just its address (Safari's Copy Image).
            var reps = representations
            // Big TIFFs (screenshots) are stored as PNG: a fraction of the size.
            if imageRep.type == UTI.tiff, imageRep.data.count > 4 * 1024 * 1024,
               !reps.contains(where: { $0.type == UTI.png }), let png = ImageTools.pngData(from: imageRep.data) {
                reps.removeAll { $0.type == UTI.tiff && $0.index == imageRep.index }
                reps.append(CapturedRepresentation(index: imageRep.index, type: UTI.png, data: png))
            }
            let size = ImageTools.pixelSize(of: imageRep.data)
            content = CapturedContent(kind: .image, text: "", identity: BlobStore.hash(imageRep.data),
                                      representations: reps, thumbnail: ImageTools.thumbnail(of: imageRep.data),
                                      imageWidth: size?.width, imageHeight: size?.height)
        } else {
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            let kind = Classifier.kind(forText: text)
            let shown = kind == .text ? text : text.trimmingCharacters(in: .whitespacesAndNewlines)
            content = CapturedContent(kind: kind, text: kind == .color ? (Classifier.hexColor(text) ?? shown) : shown,
                                      identity: shown, representations: representations)
        }
        content.representations = trimmed(content.representations)
        content.sourceBundleID = raw.sourceID
        content.sourceAppName = raw.sourceName
        return content
    }

    /// Some apps copy only RTF or HTML: their text is still searchable.
    static func textFromFormatted(_ reps: [CapturedRepresentation]) -> String? {
        if let rtf = reps.first(where: { $0.type == UTI.rtf }),
           let text = NSAttributedString(rtf: rtf.data, documentAttributes: nil)?.string {
            return text
        }
        if let html = reps.first(where: { $0.type == UTI.html }),
           let text = NSAttributedString(html: html.data, documentAttributes: nil)?.string {
            return text
        }
        return nil
    }

    /// The image format worth keeping as "the" image of a copy.
    nonisolated static func preferredImage(in reps: [CapturedRepresentation]) -> CapturedRepresentation? {
        for type in [UTI.png, UTI.tiff, UTI.jpeg, UTI.heic, "public.webp", "com.compuserve.gif"] {
            if let rep = reps.first(where: { $0.type == type }) { return rep }
        }
        return nil
    }

    /// Keeps the total size reasonable: when a copy is huge, drop the
    /// heaviest secondary formats first (apps like Office put many).
    nonisolated private static func trimmed(_ reps: [CapturedRepresentation]) -> [CapturedRepresentation] {
        var total = reps.reduce(0) { $0 + $1.data.count }
        guard total > maxTotalSize else { return reps }
        let essential: Set<String> = [UTI.plainText, UTI.rtf, UTI.html, UTI.fileURL, UTI.png, UTI.url]
        var kept = reps
        for rep in reps.sorted(by: { $0.data.count > $1.data.count }) where !essential.contains(rep.type) {
            kept.removeAll { $0.index == rep.index && $0.type == rep.type }
            total -= rep.data.count
            if total <= maxTotalSize { break }
        }
        return kept
    }
}
